language: f90
os:
  - linux
  - osx
notifications:
  email: false
script:
  - make
deploy:
  provider: releases
  api_key: "$OATH_TOKEN"
  file: "src/fortran-code.*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
